'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace CurrencyConverter
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.webserviceX.NET/", ConfigurationName:="CurrencyConverter.CurrencyConvertorSoap")>  _
    Public Interface CurrencyConvertorSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceX.NET/ConversionRate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConversionRate(ByVal FromCurrency As CurrencyConverter.Currency, ByVal ToCurrency As CurrencyConverter.Currency) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.webserviceX.NET/ConversionRate", ReplyAction:="*")>  _
        Function ConversionRateAsync(ByVal FromCurrency As CurrencyConverter.Currency, ByVal ToCurrency As CurrencyConverter.Currency) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.webserviceX.NET/")>  _
    Public Enum Currency
        
        '''<remarks/>
        AFA
        
        '''<remarks/>
        ALL
        
        '''<remarks/>
        DZD
        
        '''<remarks/>
        ARS
        
        '''<remarks/>
        AWG
        
        '''<remarks/>
        AUD
        
        '''<remarks/>
        BSD
        
        '''<remarks/>
        BHD
        
        '''<remarks/>
        BDT
        
        '''<remarks/>
        BBD
        
        '''<remarks/>
        BZD
        
        '''<remarks/>
        BMD
        
        '''<remarks/>
        BTN
        
        '''<remarks/>
        BOB
        
        '''<remarks/>
        BWP
        
        '''<remarks/>
        BRL
        
        '''<remarks/>
        GBP
        
        '''<remarks/>
        BND
        
        '''<remarks/>
        BIF
        
        '''<remarks/>
        XOF
        
        '''<remarks/>
        XAF
        
        '''<remarks/>
        KHR
        
        '''<remarks/>
        CAD
        
        '''<remarks/>
        CVE
        
        '''<remarks/>
        KYD
        
        '''<remarks/>
        CLP
        
        '''<remarks/>
        CNY
        
        '''<remarks/>
        COP
        
        '''<remarks/>
        KMF
        
        '''<remarks/>
        CRC
        
        '''<remarks/>
        HRK
        
        '''<remarks/>
        CUP
        
        '''<remarks/>
        CYP
        
        '''<remarks/>
        CZK
        
        '''<remarks/>
        DKK
        
        '''<remarks/>
        DJF
        
        '''<remarks/>
        DOP
        
        '''<remarks/>
        XCD
        
        '''<remarks/>
        EGP
        
        '''<remarks/>
        SVC
        
        '''<remarks/>
        EEK
        
        '''<remarks/>
        ETB
        
        '''<remarks/>
        EUR
        
        '''<remarks/>
        FKP
        
        '''<remarks/>
        GMD
        
        '''<remarks/>
        GHC
        
        '''<remarks/>
        GIP
        
        '''<remarks/>
        XAU
        
        '''<remarks/>
        GTQ
        
        '''<remarks/>
        GNF
        
        '''<remarks/>
        GYD
        
        '''<remarks/>
        HTG
        
        '''<remarks/>
        HNL
        
        '''<remarks/>
        HKD
        
        '''<remarks/>
        HUF
        
        '''<remarks/>
        ISK
        
        '''<remarks/>
        INR
        
        '''<remarks/>
        IDR
        
        '''<remarks/>
        IQD
        
        '''<remarks/>
        ILS
        
        '''<remarks/>
        JMD
        
        '''<remarks/>
        JPY
        
        '''<remarks/>
        JOD
        
        '''<remarks/>
        KZT
        
        '''<remarks/>
        KES
        
        '''<remarks/>
        KRW
        
        '''<remarks/>
        KWD
        
        '''<remarks/>
        LAK
        
        '''<remarks/>
        LVL
        
        '''<remarks/>
        LBP
        
        '''<remarks/>
        LSL
        
        '''<remarks/>
        LRD
        
        '''<remarks/>
        LYD
        
        '''<remarks/>
        LTL
        
        '''<remarks/>
        MOP
        
        '''<remarks/>
        MKD
        
        '''<remarks/>
        MGF
        
        '''<remarks/>
        MWK
        
        '''<remarks/>
        MYR
        
        '''<remarks/>
        MVR
        
        '''<remarks/>
        MTL
        
        '''<remarks/>
        MRO
        
        '''<remarks/>
        MUR
        
        '''<remarks/>
        MXN
        
        '''<remarks/>
        MDL
        
        '''<remarks/>
        MNT
        
        '''<remarks/>
        MAD
        
        '''<remarks/>
        MZM
        
        '''<remarks/>
        MMK
        
        '''<remarks/>
        NAD
        
        '''<remarks/>
        NPR
        
        '''<remarks/>
        ANG
        
        '''<remarks/>
        NZD
        
        '''<remarks/>
        NIO
        
        '''<remarks/>
        NGN
        
        '''<remarks/>
        KPW
        
        '''<remarks/>
        NOK
        
        '''<remarks/>
        OMR
        
        '''<remarks/>
        XPF
        
        '''<remarks/>
        PKR
        
        '''<remarks/>
        XPD
        
        '''<remarks/>
        PAB
        
        '''<remarks/>
        PGK
        
        '''<remarks/>
        PYG
        
        '''<remarks/>
        PEN
        
        '''<remarks/>
        PHP
        
        '''<remarks/>
        XPT
        
        '''<remarks/>
        PLN
        
        '''<remarks/>
        QAR
        
        '''<remarks/>
        ROL
        
        '''<remarks/>
        RUB
        
        '''<remarks/>
        WST
        
        '''<remarks/>
        STD
        
        '''<remarks/>
        SAR
        
        '''<remarks/>
        SCR
        
        '''<remarks/>
        SLL
        
        '''<remarks/>
        XAG
        
        '''<remarks/>
        SGD
        
        '''<remarks/>
        SKK
        
        '''<remarks/>
        SIT
        
        '''<remarks/>
        SBD
        
        '''<remarks/>
        SOS
        
        '''<remarks/>
        ZAR
        
        '''<remarks/>
        LKR
        
        '''<remarks/>
        SHP
        
        '''<remarks/>
        SDD
        
        '''<remarks/>
        SRG
        
        '''<remarks/>
        SZL
        
        '''<remarks/>
        SEK
        
        '''<remarks/>
        CHF
        
        '''<remarks/>
        SYP
        
        '''<remarks/>
        TWD
        
        '''<remarks/>
        TZS
        
        '''<remarks/>
        THB
        
        '''<remarks/>
        TOP
        
        '''<remarks/>
        TTD
        
        '''<remarks/>
        TND
        
        '''<remarks/>
        TRL
        
        '''<remarks/>
        USD
        
        '''<remarks/>
        AED
        
        '''<remarks/>
        UGX
        
        '''<remarks/>
        UAH
        
        '''<remarks/>
        UYU
        
        '''<remarks/>
        VUV
        
        '''<remarks/>
        VEB
        
        '''<remarks/>
        VND
        
        '''<remarks/>
        YER
        
        '''<remarks/>
        YUM
        
        '''<remarks/>
        ZMK
        
        '''<remarks/>
        ZWD
        
        '''<remarks/>
        [TRY]
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CurrencyConvertorSoapChannel
        Inherits CurrencyConverter.CurrencyConvertorSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CurrencyConvertorSoapClient
        Inherits System.ServiceModel.ClientBase(Of CurrencyConverter.CurrencyConvertorSoap)
        Implements CurrencyConverter.CurrencyConvertorSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ConversionRate(ByVal FromCurrency As CurrencyConverter.Currency, ByVal ToCurrency As CurrencyConverter.Currency) As Double Implements CurrencyConverter.CurrencyConvertorSoap.ConversionRate
            Return MyBase.Channel.ConversionRate(FromCurrency, ToCurrency)
        End Function
        
        Public Function ConversionRateAsync(ByVal FromCurrency As CurrencyConverter.Currency, ByVal ToCurrency As CurrencyConverter.Currency) As System.Threading.Tasks.Task(Of Double) Implements CurrencyConverter.CurrencyConvertorSoap.ConversionRateAsync
            Return MyBase.Channel.ConversionRateAsync(FromCurrency, ToCurrency)
        End Function
    End Class
End Namespace
